import unittest
import pprint as pp
from collections import OrderedDict

from download_tables import TableExtractor


class TestTableExtractor(unittest.TestCase):
	def setUp(self):
		self.test_extractor = TableExtractor()

	def test_download_verb_tables(self):
		'''
		'getmək' - cлучай, когда на странице есть таблица и она нужная.
		'asmaq' - случай, когда на странице нет таблицы.
		'aprel' - случай, когда слово другой части речи и таблица есть, но она неподходящего формата (т.е. та, которую извлекать не нужно).
		:return:
		'''
		test_data = ['getmək', 'asmaq', 'aprel']
		true_result = (OrderedDict([('getmək',
									[OrderedDict([('getmişdim', OrderedDict(
										[('Form', '-mişdi_past'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('getdim',
												   OrderedDict([('Form', '-di_past'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('gedirəm',
												   OrderedDict([('Form', 'present'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('gedəcəyəm',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('gedərəm',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '1_sing')]))]),
									 OrderedDict(
										 [('gedim', OrderedDict([('Form', 'imp'), ('Person-Number', '1_sing')]))]),
									 OrderedDict(
										 [('gedəm', OrderedDict([('Form', 'arzu'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('getməliyəm',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('gedəsiyəm',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '1_sing')]))]),
									 OrderedDict(
										 [('getsəm', OrderedDict([('Form', 'şərt'), ('Person-Number', '1_sing')]))]),
									 OrderedDict([('getmək', OrderedDict([('Form', 'inf'), ('Case', 'nom')]))]),
									 OrderedDict([('getmişdin', OrderedDict(
										 [('Form', '-mişdi_past'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('getdin',
												   OrderedDict([('Form', '-di_past'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('gedirsən',
												   OrderedDict([('Form', 'present'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('gedəcəksən',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('gedərsən',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '2_sing')]))]),
									 OrderedDict(
										 [('get', OrderedDict([('Form', 'imp'), ('Person-Number', '2_sing')]))]),
									 OrderedDict(
										 [('gedəsən', OrderedDict([('Form', 'arzu'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('getməlisən',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('gedəsisən',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '2_sing')]))]),
									 OrderedDict(
										 [('getsən', OrderedDict([('Form', 'şərt'), ('Person-Number', '2_sing')]))]),
									 OrderedDict([('getməyin', OrderedDict([('Form', 'inf'), ('Case', 'gen')]))]),
									 OrderedDict([('getmişdi', OrderedDict(
										 [('Form', '-mişdi_past'), ('Person-Number', '3_sing')]))]),
									 OrderedDict(
										 [('getdi', OrderedDict([('Form', '-di_past'), ('Person-Number', '3_sing')]))]),
									 OrderedDict(
										 [('gedir', OrderedDict([('Form', 'present'), ('Person-Number', '3_sing')]))]),
									 OrderedDict([('gedəcək',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '3_sing')]))]),
									 OrderedDict([('gedər',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '3_sing')]))]),
									 OrderedDict(
										 [('getsin', OrderedDict([('Form', 'imp'), ('Person-Number', '3_sing')]))]),
									 OrderedDict(
										 [('gedə', OrderedDict([('Form', 'arzu'), ('Person-Number', '3_sing')]))]),
									 OrderedDict([('getməlidir',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '3_sing')]))]),
									 OrderedDict([('gedəsidir',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '3_sing')]))]),
									 OrderedDict(
										 [('getsə', OrderedDict([('Form', 'şərt'), ('Person-Number', '3_sing')]))]),
									 OrderedDict([('getməyə', OrderedDict([('Form', 'inf'), ('Case', 'dat')]))]),
									 OrderedDict([('getmişdik', OrderedDict(
										 [('Form', '-mişdi_past'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('getdik',
												   OrderedDict([('Form', '-di_past'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('gedirik',
												   OrderedDict([('Form', 'present'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('gedəcəyik',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('gedərik',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '1_plur')]))]),
									 OrderedDict(
										 [('gedək', OrderedDict([('Form', 'imp'), ('Person-Number', '1_plur')]))]),
									 OrderedDict(
										 [('gedək', OrderedDict([('Form', 'arzu'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('getməliyik',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('gedəsiyik',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '1_plur')]))]),
									 OrderedDict(
										 [('getsək', OrderedDict([('Form', 'şərt'), ('Person-Number', '1_plur')]))]),
									 OrderedDict([('getməyi', OrderedDict([('Form', 'inf'), ('Case', 'acc')]))]),
									 OrderedDict([('getmişdiniz', OrderedDict(
										 [('Form', '-mişdi_past'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('getdiniz',
												   OrderedDict([('Form', '-di_past'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('gedirsiniz',
												   OrderedDict([('Form', 'present'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('gedəcəksiniz',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('gedərsiniz',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '2_plur')]))]),
									 OrderedDict(
										 [('gedəsiniz', OrderedDict([('Form', 'imp'), ('Person-Number', '2_plur')]))]),
									 OrderedDict(
										 [('gedəsiniz', OrderedDict([('Form', 'arzu'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('getməlisiniz',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('gedəsisiniz',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '2_plur')]))]),
									 OrderedDict(
										 [('getsəniz', OrderedDict([('Form', 'şərt'), ('Person-Number', '2_plur')]))]),
									 OrderedDict([('getməkdə', OrderedDict([('Form', 'inf'), ('Case', 'loc')]))]),
									 OrderedDict([('getmişdilər', OrderedDict(
										 [('Form', '-mişdi_past'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('getdilər',
												   OrderedDict([('Form', '-di_past'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('gedirlər',
												   OrderedDict([('Form', 'present'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('gedəcəklər',
												   OrderedDict([('Form', 'fut_def'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('gedərlər',
												   OrderedDict([('Form', 'fut_indef'), ('Person-Number', '3_plur')]))]),
									 OrderedDict(
										 [('getsinlər', OrderedDict([('Form', 'imp'), ('Person-Number', '3_plur')]))]),
									 OrderedDict(
										 [('gedələr', OrderedDict([('Form', 'arzu'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('getməlidirlər',
												   OrderedDict([('Form', 'vacib'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('gedəsidirlər',
												   OrderedDict([('Form', 'lazım'), ('Person-Number', '3_plur')]))]),
									 OrderedDict(
										 [('getsələr', OrderedDict([('Form', 'şərt'), ('Person-Number', '3_plur')]))]),
									 OrderedDict([('getməkdən', OrderedDict([('Form', 'inf'), ('Case', 'abl')]))])
									 ]
									)]),1,66)
		fact_result = self.test_extractor.download_verb_tables(test_data)
		self.assertDictEqual(true_result[0], fact_result[0])
		self.assertEqual(true_result[1], fact_result[1])
		self.assertEqual(true_result[2], fact_result[2])

	def test_download_noun_tables(self):
		'''
		Тест для функции download_noun_tables.
		Рассмотрению подлежат следующие случаи:
		1) на странице нет таблиц;
		2) таблица склонения по падежам и числам может содержать иллюстрации в 1-2 первых строках => случай с иллюстрацией;
		3) случай без иллюстрации;
		4) таблица притяжательных форм с формами только ед.ч.;
		5) таблица притяжательных форм со всеми формами;
		6) есть только таблица склонения по падежам и числам;
		7) есть обе таблицы;
		8) на странице присутствуют другие языки, для которые также есть таблицы верного формата;
		9) слово - не существительное, на странице есть таблица.
		Рассмотрены слова, описывающие эти случаи:
		'ana' - 2, 4, 7, 8
		'ev' - 2, 5, 7, 8
		'qərargah' - 1
		'abadlıq' - 3, 6
		'getmək' - 9
		:return: 
		'''
		test_data = ['ana', 'ev', 'qərargah', 'abadlıq','getmək']
		true_result = (OrderedDict([('ana',
									[OrderedDict([('ana', OrderedDict([('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('analar', OrderedDict([('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('ananın', OrderedDict([('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anaların', OrderedDict([('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('anaya', OrderedDict([('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('analara', OrderedDict([('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('ananı', OrderedDict([('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('anaları', OrderedDict([('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('anada', OrderedDict([('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('analarda', OrderedDict([('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('anadan', OrderedDict([('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('analardan', OrderedDict([('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict(
										 [('anam', OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('anamın',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anama',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('anamı',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('anamda',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('anamdan',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict(
										 [('anan', OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('ananın',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anana',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('ananı',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('ananda',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('anandan',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('anası',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('anasının',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anasına',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('anasını',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('anasında',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('anasından',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('anamız',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('anamızın',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anamıza',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('anamızı',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('anamızda',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('anamızdan',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('ananız',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('ananızın',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('ananıza',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('ananızı',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('ananızda',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('ananızdan',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('anası',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('anasının',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('anasına',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('anasını',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('anasında',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('anasından',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))])]),
									('ev',
									[OrderedDict([('ev', OrderedDict([('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evlər', OrderedDict([('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evin', OrderedDict([('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərin', OrderedDict([('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evə', OrderedDict([('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərə', OrderedDict([('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evi', OrderedDict([('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evləri', OrderedDict([('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evdə', OrderedDict([('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərdə', OrderedDict([('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evdən', OrderedDict([('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərdən', OrderedDict([('Number', 'plur'), ('Case', 'abl')]))]),

									 OrderedDict(
										 [('evim', OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evlərim',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evimin',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərimin',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evimə',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərimə',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evimi',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərimi',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evimdə',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərimdə',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evimdən',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərimdən',
												   OrderedDict([('Person-Number_psor', '1_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict(
										 [('evin', OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evlərin',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evinin',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərinin',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evinə',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərinə',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evini',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərini',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evində',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərində',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evindən',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərindən',
												   OrderedDict([('Person-Number_psor', '2_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict(
										 [('evi', OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
															   ('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evləri',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evinin',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərinin',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evinə',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərinə',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evini',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərini',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evində',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərində',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evindən',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərindən',
												   OrderedDict([('Person-Number_psor', '3_sing'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict([('evimiz',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evlərimiz',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evimizin',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərimizin',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evimizə',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərimizə',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evimizi',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərimizi',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evimizdə',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərimizdə',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evimizdən',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərimizdən',
												   OrderedDict([('Person-Number_psor', '1_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict([('eviniz',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evləriniz',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evinizin',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərinizin',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evinizə',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərinizə',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evinizi',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərinizi',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evinizdə',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərinizdə',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evinzidən',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərinizdən',
												   OrderedDict([('Person-Number_psor', '2_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))]),
									 OrderedDict(
										 [('evi', OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
															   ('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('evləri',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('evinin',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('evlərinin',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('evinə',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('evlərinə',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('evini',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('evlərini',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('evində',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('evlərində',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('evindən',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('evlərindən',
												   OrderedDict([('Person-Number_psor', '3_plur'), ('Possession', 'pos'),
																('Number', 'plur'), ('Case', 'abl')]))])]),
								   ('abadlıq',
									[OrderedDict([('abadlıq', OrderedDict([('Number', 'sing'), ('Case', 'nom')]))]),
									 OrderedDict([('abadlıqlar', OrderedDict([('Number', 'plur'), ('Case', 'nom')]))]),
									 OrderedDict([('abadlığın', OrderedDict([('Number', 'sing'), ('Case', 'gen')]))]),
									 OrderedDict([('abadlıqların', OrderedDict([('Number', 'plur'), ('Case', 'gen')]))]),
									 OrderedDict([('abadlığa', OrderedDict([('Number', 'sing'), ('Case', 'dat')]))]),
									 OrderedDict([('abadlıqlara', OrderedDict([('Number', 'plur'), ('Case', 'dat')]))]),
									 OrderedDict([('abadlığı', OrderedDict([('Number', 'sing'), ('Case', 'acc')]))]),
									 OrderedDict([('abadlıqları', OrderedDict([('Number', 'plur'), ('Case', 'acc')]))]),
									 OrderedDict([('abadlıqda', OrderedDict([('Number', 'sing'), ('Case', 'loc')]))]),
									 OrderedDict([('abadlıqlarda', OrderedDict([('Number', 'plur'), ('Case', 'loc')]))]),
									 OrderedDict([('abadlıqdan', OrderedDict([('Number', 'sing'), ('Case', 'abl')]))]),
									 OrderedDict([('abadlıqlardan', OrderedDict([('Number', 'plur'), ('Case', 'abl')]))])
									 ]
									)]),3,144)
		fact_result = self.test_extractor.download_noun_tables(test_data)
		self.assertDictEqual(true_result[0], fact_result[0])
		self.assertEqual(true_result[1], fact_result[1])
		self.assertEqual(true_result[2], fact_result[2])

if __name__ == '__main__':
	unittest.main()
